[options]

admin_passwd = 4dm1n7ic
db_host = localhost
db_port = 5422
db_user = odoo
db_password = odoo
; Puerto donde correrá Odoo
http_port = 8025

; RUTAS DE ADDONS - SÓLO ESTAS DOS
addons_path = /home/sugau/source/odoo-18.0.post20251118/odoo-18.0.post20251118,/home/sugau/Projects/odoo18-dev/custom_addons

; Directorio de datos
data_dir = /home/sugau/Projects/odoo18-dev/.local/share/Odoo

; Configuración de logging
logfile = /home/sugau/Projects/odoo18-dev/odoo.log
log_level = info




